---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.7.0 # This should be kept in sync with the version in requirements-dev.in
    hooks:
      - id: black
        args: ["--preview"]
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.7.0 # This should be kept in sync with the version in requirements-dev.in
    hooks:
      - id: autopep8
        args: ["--exit-code", "--in-place"]
        files: gnomad_constraint
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1 # This should be kept in sync with the version in requirements-dev.in
    hooks:
      - id: pydocstyle
        args: ["--convention=pep257"]
        additional_dependencies: ["toml"]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0 # This should be kept in sync with the version in requirements-dev.in
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        files: gnomad_constraint
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3  # Use the latest release
    hooks:
      - id: style-files
  - repo: local
    hooks:
      - id: lintr
        name: lintr
        entry: Rscript -e "renv::restore(); lintr::lint_dir('gnomad_constraint/plots/', pattern='.R$')"
        language: system
        types: [r]
        pass_filenames: false
