[tool.pydocstyle]
convention = "pep257"
match = ".*\\.py"
add_ignore = [
  "D100", # Do not require docstrings for modules.
  "D104", # Do not require docstrings for packages (in __init__.py).
]

[tool.pylint.messages_control]
disable = [
  # Ignore refactor and convention categories
  "R",
  "C",
  # Allow todo/fixme comments
  "fixme",
  # Warnings
  "cell-var-from-loop",
  "dangerous-default-value",
  "invalid-unary-operand-type",
  "pointless-string-statement",
  "protected-access",
  "redefined-outer-name",
  "unspecified-encoding",
  "unused-variable",
]

[tool.black]
target-version = ['py36', 'py37', 'py38']
preview = true

[tool.isort]
profile = "black"

[tool.autopep8]
# Use same max line length as the default in Black - 88
max_line_length = 88
# Ignore errors that conflict with Black
# E201 - whitespace after ‘(‘
# E202 - whitespace before ‘)’
# E203 - whitespace before ‘:’
# Ignore E731 - do not assign a lambda expression, use a def
ignore = ['E201', 'E202', 'E203', 'E731']
recursive = true
aggressive = 1
