name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4
      - name: Use pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            pip-
      - name: Install Python dependencies
        run: |
          pip install wheel
          pip install -r requirements-dev.txt
          pip install hail
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Install R dependencies
        run: |
          install.packages(c("lintr", "styler"))
      - name: Check formatting
        run: black --check --preview gnomad_constraint
      - name: Check imports
        run: isort --check-only gnomad_constraint
      - name: Check docstrings
        run: pydocstyle
      - name: Check comment formatting
        run: autopep8 --exit-code --diff gnomad_constraint
      - name: Run Pylint
        run: PYTHONPATH=$(pwd):$PYTHONPATH pylint --disable=W gnomad_constraint
      - name: Run styler
        run: Rscript -e "styler::style_dir('gnomad_constraint/plots/')"
      - name: Run lintr
        run: Rscript -e "lintr::lint_dir('gnomad_constraint/plots/', pattern='.R$')"
